version: '1'

services:
  ddnsbot:
    build: .
    image: abelroes/telegram-ddnsbot
    container_name: ddnsbot
    environment:
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_PORT=${SERVICE_PORT}
      - DDNS_BOT_TOKEN=${DDNS_BOT_TOKEN}
      - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
