version: '2.1'

services:
  telegram-ddnsbot:
    build: .
    image: abelroes/telegram-ddnsbot
    environment:
      - DDNS_BOT_TOKEN=${DDNS_BOT_TOKEN}
      - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_PORT=${SERVICE_PORT}
